spring:
  datasource:
    url: jdbc:mysql://localhost/planeat
    username: planeat
    password: planeat
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect


# Root User: adminxk7RqgE
#   Root Password: GdvJu29zbXmR
#   Database Name: planeat
