spring:
  datasource:
    url: jdbc:mysql://127.7.202.2:3306/planeat
    username: adminBhczhvk
    password: yQHeEg4aLtDA
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  file: ${OPENSHIFT_DATA_DIR}/logs/app.log
